Nhom15/Models/TaiKhoanKhachHang.cs
namespace Nhom15.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TaiKhoanKhachHang")]
    public partial class TaiKhoanKhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoanKhachHang()
        {
            ChiTietGioHangs = new HashSet<ChiTietGioHang>();
            HoaDons = new HashSet<HoaDon>();
        }

        [Key]
        [StringLength(50)]
        public string Username { get; set; }

        [StringLength(20)]
        public string Password { get; set; }

        [StringLength(50)]
        public string HoTen { get; set; }

        [StringLength(50)]
        public string Email { get; set; }

        [StringLength(12)]
        public string SDT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}

Nhom15/Areas/Admin/Controllers/TaikhoanKhachhangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom15.Models;
using PagedList;

namespace Nhom15.Areas.Admin.Controllers
{
    public class TaikhoanKhachhangsController : BaseController
    {

        private Nhom15DbContext db = new Nhom15DbContext();
        // GET: Admin/TaikhoanKhachhangs
        public ActionResult Index(string sortOrder, int? page)
        {
            ViewBag.SaptheoTen = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var acc = db.TaiKhoanKhachHangs.Select(a => a);

            switch (sortOrder)
            {
                case "name_desc":
                    acc = acc.OrderByDescending(s => s.Username);
                    break;
                default:
                    acc = acc.OrderBy(s => s.Username);
                    break;
            }

            int pageSize = 7;
            int pageNumber = (page ?? 1);

            return View(acc.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoanKhachHang taikhoan = db.TaiKhoanKhachHangs.Find(id);
            if (taikhoan == null)
            {
                return HttpNotFound();
            }
            return View(taikhoan);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TaiKhoanKhachHang taikhoan = db.TaiKhoanKhachHangs.Find(id);
            try
            {
                db.TaiKhoanKhachHangs.Remove(taikhoan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Flag = 1;
                return View("Delete", taikhoan);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AccountModel model)
        {
            if (ModelState.IsValid)
            {
                if (checkKey(model.Username))
                {
                    ViewBag.Flag = 1;
                    return View(model);
                }
                else
                {
                    var acc = new TaiKhoanKhachHang();
                    acc.Username = model.Username;
                    acc.Password = model.Password;
                    acc.HoTen = model.HoTen;
                    acc.Email = model.Email;
                    acc.SDT = model.SDT;
                    db.TaiKhoanKhachHangs.Add(acc);
                    var result = db.SaveChanges();
                    if (result > 0)
                    {
                        ViewBag.Flag = 1;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Flag = 0;
                        return View(model);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoanKhachHang tk = db.TaiKhoanKhachHangs.Find(id);

            if (tk == null)
            {
                return HttpNotFound();
            }

            var acc = new AccountModel();
            acc.Username = tk.Username;
            acc.Password = tk.Password;
            acc.ConfirmPassword = tk.Password;
            acc.HoTen = tk.HoTen;
            acc.Email = tk.Email;
            acc.SDT = tk.SDT;

            return View(acc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AccountModel model)
        {
            if (ModelState.IsValid)
            {
                var tk = db.TaiKhoanKhachHangs.Find(model.Username);
                tk.Password = model.Password;
                tk.HoTen = model.HoTen;
                tk.Email = model.Email;
                tk.SDT = model.SDT;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        private bool checkKey(string key)
        {
            return db.TaiKhoanKhachHangs.Count(u => u.Username == key) > 0;
        }

    }
}

Nhom15/Controllers/TaiKhoanKhachHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom15.Models;

namespace Nhom15.Controllers
{
    public class TaiKhoanKhachHangsController : Controller
    {
        private Nhom15DbContext db = new Nhom15DbContext();

        public ActionResult DangNhap()
        {
            return View();
        }

        // GET: TaiKhoans/Create
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(string email, string matkhau)
        {
            if (ModelState.IsValid)
            {
                var user = db.TaiKhoanKhachHangs.Where(u => u.Username.Equals(email) && u.Password.Equals(matkhau));
                if (user.Count() > 0)
                {
                    Session["User"] = user.FirstOrDefault().Username;
                    Session["HoTen"] = user.FirstOrDefault().HoTen;
                    Session["Email"] = user.FirstOrDefault().Email;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Error = "Đăng nhập không thành công!";
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult DangKy([Bind(Include = "Username,Password,HoTen,Email,SDT")] TaiKhoanKhachHang taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.TaiKhoanKhachHangs.Add(taiKhoan);
                db.SaveChanges();
                return RedirectToAction("DangNhap");
            }

            return View(taiKhoan);
        }

        public ActionResult ChiTiet()
        {
            String username = (string)Session["User"];
            TaiKhoanKhachHang user = db.TaiKhoanKhachHangs.Where(u => u.Username == username).FirstOrDefault();
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChiTiet([Bind(Include = "username,password,HoTen,Email,IsAdmin,SDT")] TaiKhoanKhachHang taiKhoan)
        {
            if (ModelState.IsValid)
            {
                String username = (string)Session["User"];
                TaiKhoanKhachHang user = db.TaiKhoanKhachHangs.Where(u => u.Username == username).FirstOrDefault();
                //user.username = taiKhoan.username;
                user.Password = taiKhoan.Password;
                user.HoTen = taiKhoan.HoTen;
                user.Email = taiKhoan.Email;
                user.SDT = taiKhoan.SDT;
                db.SaveChanges();
                ViewBag.Ok = "Cập nhập thành công";
                Session["HoTen"] = taiKhoan.HoTen;
                return View(taiKhoan);
            }
            return View(taiKhoan);
        }


    }
}

Nhom15/Areas/Admin/Views/TaikhoanKhachhangs/Create.cshtml
@model Nhom15.Models.AccountModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.Flag == 1)
{
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Tên đăng nhập đã tồn tại
    </div>
}

@if (ViewBag.Flag == 0)
{
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Thêm mới không thành công
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Thêm mới tài khoản khách hàng</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Tên đăng nhập</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Mật khẩu</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Xác nhận mật khẩu</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Họ tên</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Email</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Số điện thoại</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="margin-top:15px;">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm mới" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <a class="btn btn-primary" href="/Admin/TaikhoanKhachhangs/Index" role="button" style="margin-top: 15px;">Quay lại</a>
</div>

Nhom15/Areas/Admin/Views/TaikhoanKhachhangs/Delete.cshtml
@model Nhom15.Models.TaiKhoanKhachHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.Flag == 1)
{
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Không thể xóa bản ghi này!
    </div>
}

<h3>Bạn có chắc muốn xóa tài khoản này?</h3>
<div>
    <hr />
    <table>
        <thead>
            <tr>
                <th style="width: 200px">Tên tài khoản</th>
                <th style="width: 200px">Mật khẩu</th>
                <th style="width: 200px">Họ tên</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayFor(model => model.Username)</td>
                <td>@Html.DisplayFor(model => model.Password)</td>
                <td>@Html.DisplayFor(model => model.HoTen)</td>
            </tr>
        </tbody>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group" style="margin-top:15px;">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Xóa" class="btn btn-danger" />
            </div>
        </div>
        <div>
            <a class="btn btn-primary" href="/Admin/TaiKhoanKhachHangs/Index" role="button" style="margin-top: 15px;">Quay lại</a>
        </div>
    }
</div>

Nhom15/Areas/Admin/Views/TaikhoanKhachhangs/Edit.cshtml
@model Nhom15.Models.AccountModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.Flag == 0)
{
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Cập nhật không thành công
    </div>
}

@using (Html.BeginForm("Edit", "TaikhoanKhachhangs", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Cập nhật tài khoản khách hàng</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Username)

    <div class="form-group">
        <label class="control-label col-md-2">Mật khẩu</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Xác nhận mật khẩu</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Họ tên</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Email</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Số điện thoại</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="margin-top:15px;">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Cập nhật" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <a class="btn btn-primary" href="/Admin/TaikhoanKhachhangs/Index" role="button" style="margin-top: 15px;">Quay lại</a>
</div>

Nhom15/Areas/Admin/Views/TaikhoanKhachhangs/Index.cshtml
@model PagedList.IPagedList<Nhom15.Models.TaiKhoanKhachHang>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.Flag == 1)
{
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Thêm mới thành công
    </div>
}

<h4 class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300">
    Danh sách tài khoản khách hàng
</h4>

<div class="col-md-1" style="margin-bottom: 15px;">
    <a class="btn btn-success" href="/Admin/TaikhoanKhachhangs/Create" role="button"><i class="fas fa-plus-square"></i> Thêm</a>
</div>

<div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
        <table class="w-full whitespace-no-wrap">
            <thead>
                <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                    <th class="px-4 py-3">
                        @Html.ActionLink("Tên đăng nhập", "Index", new { sortOrder = ViewBag.Saptheoten })
                    </th>
                    <th class="px-4 py-3">mật khẩu</th>
                    <th class="px-4 py-3">Họ tên</th>
                    <th class="px-4 py-3">Email</th>
                    <th class="px-4 py-3">Số điện thoại</th>
                    <th class="px-4 py-3">Thao tác</th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                @foreach (var item in Model)
                {
                <tr class="text-gray-700 dark:text-gray-400">
                    <td class="px-4 py-3">
                        <div class="flex items-center text-sm">
                            <div>
                                <p class="font-semibold">@Html.DisplayFor(model => item.Username)</p>
                            </div>
                        </div>
                    </td>
                    <td class="px-4 py-3 text-sm">
                        @Html.DisplayFor(model => item.Password)
                    </td>
                    <td class="px-4 py-3 text-sm">
                        @Html.DisplayFor(model => item.HoTen)
                    </td>
                    <td class="px-4 py-3 text-sm">
                        @Html.DisplayFor(model => item.Email)
                    </td>
                    <td class="px-4 py-3 text-sm">
                        @Html.DisplayFor(model => item.SDT)
                    </td>
                    <td class="px-4 py-3 text-xs">
                        <div class="col-md-1" style="margin-bottom: 15px;">
                            <a class="btn btn-primary" href="/Admin/TaikhoanKhachhangs/Edit/@item.Username.Trim()" role="button"><i class="fas fa-pen-square"></i> Sửa</a>
                            <a class="btn btn-danger" href="/Admin/TaikhoanKhachhangs/Delete/@item.Username.Trim()" role="button"><i class="fas fa-trash-alt"></i> Xóa</a>
                        </div>
                    </td>
                </tr>
                }

            </tbody>
        </table>
    </div>
    <div style="margin-top: 15px;">
        @Html.PagedListPager(
        Model, page => Url.Action("Index", new { page }),
        new PagedListRenderOptions()
        {
        LiElementClasses = new List<string> { "btn", "btn-warning" }
        })
    </div>