Nhom15/Models/TaiKhoanAdmin.cs
namespace Nhom15.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TaiKhoanAdmin")]
    public partial class TaiKhoanAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoanAdmin()
        {
            TinTucs = new HashSet<TinTuc>();
        }

        [Key]
        [StringLength(50)]
        public string Username { get; set; }

        [StringLength(20)]
        public string Password { get; set; }

        public bool? FullControl { get; set; }

        [StringLength(50)]
        public string HoTen { get; set; }

        [StringLength(50)]
        public string Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinTuc> TinTucs { get; set; }
    }
}

Nhom15/Areas/Admin/Controllers/TaikhoanAdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom15.Models;
using PagedList;

namespace Nhom15.Areas.Admin.Controllers
{
    public class TaikhoanAdminsController : BaseController
    {
        private Nhom15DbContext db = new Nhom15DbContext();

        // GET: Admin/TaikhoanAdmins
        public ActionResult Index(string sortOrder, int? page)
        {
            ViewBag.SaptheoTen = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var acc = db.TaiKhoanAdmins.Where(s => s.FullControl == false).Select(a => a);

            switch (sortOrder)
            {
                case "name_desc":
                    acc = acc.OrderByDescending(s => s.Username);
                    break;
                default:
                    acc = acc.OrderBy(s => s.Username);
                    break;
            }

            int pageSize = 7;
            int pageNumber = (page ?? 1);

            return View(acc.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AccountModel model)
        {
            if (ModelState.IsValid)
            {
                if (checkKey(model.Username))
                {
                    ViewBag.Flag = 1;
                    return View(model);
                }
                else
                {
                    var admin = new TaiKhoanAdmin();
                    admin.Username = model.Username;
                    admin.Password = model.Password;
                    admin.HoTen = model.HoTen;
                    admin.Email = model.Email;
                    admin.FullControl = false;
                    db.TaiKhoanAdmins.Add(admin);
                    var result = db.SaveChanges();
                    if(result > 0)
                    {
                        ViewBag.Flag = 1;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Flag = 0;
                        return View(model);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoanAdmin tk = db.TaiKhoanAdmins.Find(id);
            
            if (tk == null)
            {
                return HttpNotFound();
            }

            var acc = new AccountModel();
            acc.Username = tk.Username;
            acc.Password = tk.Password;
            acc.ConfirmPassword = tk.Password;
            acc.HoTen = tk.HoTen;
            acc.Email = tk.Email;

            return View(acc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AccountModel model)
        {
            if (ModelState.IsValid)
            {
                var admin = db.TaiKhoanAdmins.Find(model.Username);
                admin.Password = model.Password;
                admin.HoTen = model.HoTen;
                admin.Email = model.Email;
                admin.FullControl = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoanAdmin tk = db.TaiKhoanAdmins.Find(id);
            if (tk == null)
            {
                return HttpNotFound();
            }
            return View(tk);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TaiKhoanAdmin tk = db.TaiKhoanAdmins.Find(id);
            try
            {
                db.TaiKhoanAdmins.Remove(tk);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Flag = 1;
                return View("Delete", tk);
            }
        }

        public ActionResult Profile()
        {
            string username = (string)Session["Username"];
            var tk = db.TaiKhoanAdmins.Find(username);

            return View(tk);
        }

        private bool checkKey(string key)
        {
            return db.TaiKhoanAdmins.Count(u => u.Username == key) > 0;
        }
    }
}

Nhom15/Areas/Admin/Views/TaikhoanAdmins/Create.cshtml
@model Nhom15.Models.AccountModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.Flag == 1)
{
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Tên đăng nhập đã tồn tại
    </div>
}

@if (ViewBag.Flag == 0)
{
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Thêm mới không thành công
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm mới tài khoản Admin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tên đăng nhập</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mật khẩu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Xác nhận mật khẩu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Họ tên</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Email</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-top:15px;">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-primary" href="/Admin/TaikhoanAdmins/Index" role="button" style="margin-top: 15px;">Quay lại</a>
</div>

Nhom15/Areas/Admin/Views/TaikhoanAdmins/Delete.cshtml
@model Nhom15.Models.TaiKhoanAdmin

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaiKhoanAdmin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mật khẩu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            Quyền
        </dt>

        <dd>
            Admin
        </dd>

        <dt>
            Họ tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group" style="margin-top:15px;">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Xóa" class="btn btn-danger" />
            </div>
        </div>
        <div>
            <a class="btn btn-primary" href="/Admin/TaikhoanAdmins/Index" role="button" style="margin-top: 15px;">Quay lại</a>
        </div>
    }
</div>

Nhom15/Areas/Admin/Views/TaikhoanAdmins/Edit.cshtml
@model Nhom15.Models.AccountModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.Flag == 0)
{
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Cập nhật không thành công
    </div>
}

@using (Html.BeginForm("Edit","TaikhoanAdmins",FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Cập nhật tài khoản Admin</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Username)

    <div class="form-group">
        <label class="control-label col-md-2">Mật khẩu</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Xác nhận mật khẩu</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Họ tên</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Email</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="margin-top:15px;">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Cập nhật" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <a class="btn btn-primary" href="/Admin/TaikhoanAdmins/Index" role="button" style="margin-top: 15px;">Quay lại</a>
</div>

Nhom15/Areas/Admin/Views/TaikhoanAdmins/Index.cshtml
@model PagedList.IPagedList<Nhom15.Models.TaiKhoanAdmin>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.Flag == 1)
{
    <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        Thêm mới thành công
    </div>
}

<h4 class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300">
    Danh sách Admin
</h4>

<div class="col-md-1" style="margin-bottom: 15px;">
    <a class="btn btn-success" href="/Admin/TaikhoanAdmins/Create" role="button"><i class="fas fa-plus-square"></i> Thêm</a>
</div>

<div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
        <table class="w-full whitespace-no-wrap">
            <thead>
                <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
                    <th class="px-4 py-3">
                        @Html.ActionLink("Tên đăng nhập", "Index", new { sortOrder = ViewBag.Saptheoten })
                    </th>
                    <th class="px-4 py-3">mật khẩu</th>
                    <th class="px-4 py-3">Họ tên</th>
                    <th class="px-4 py-3">Email</th>
                    <th class="px-4 py-3">Thao tác</th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
                @foreach (var item in Model)
                {
                    <tr class="text-gray-700 dark:text-gray-400">
                        <td class="px-4 py-3">
                            <div class="flex items-center text-sm">
                                <div>
                                    <p class="font-semibold">@Html.DisplayFor(model => item.Username)</p>
                                </div>
                            </div>
                        </td>
                        <td class="px-4 py-3 text-sm">
                            @Html.DisplayFor(model => item.Password)
                        </td>
                        <td class="px-4 py-3 text-sm">
                            @Html.DisplayFor(model => item.HoTen)
                        </td>
                        <td class="px-4 py-3 text-sm">
                            @Html.DisplayFor(model => item.Email)
                        </td>
                        <td class="px-4 py-3 text-xs">
                            <div class="col-md-1" style="margin-bottom: 15px;">
                                <a class="btn btn-primary" href="/Admin/TaikhoanAdmins/Edit/@item.Username.Trim()" role="button"><i class="fas fa-pen-square"></i> Sửa</a>
                                @*<a class="btn btn-primary" href="/Admin/Hoadons/Details/@item.MaHoaDon.Trim()" role="button"><i class="fas fa-info-circle"></i> Chi tiết</a>*@
                                <a class="btn btn-danger" href="/Admin/TaikhoanAdmins/Delete/@item.Username.Trim()" role="button"><i class="fas fa-trash-alt"></i> Xóa</a>
                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
    <div style="margin-top: 15px;">
        @Html.PagedListPager(
        Model, page => Url.Action("Index", new { page }),
        new PagedListRenderOptions()
        {
        LiElementClasses = new List<string> { "btn", "btn-warning" }
        })
    </div>

Nhom15/Areas/Admin/Views/TaikhoanAdmins/Profile.cshtml
@model Nhom15.Models.TaiKhoanAdmin

@{
    ViewBag.Title = "Profile";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h4>Thông tin tài khoản</h4>
<table class="w-full whitespace-no-wrap">
    <thead>
        <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
            <th class="px-4 py-3">
                Tên đăng nhập
            </th>
            <th class="px-4 py-3">mật khẩu</th>
            <th class="px-4 py-3">Họ tên</th>
            <th class="px-4 py-3">Email</th>
        </tr>
    </thead>
    <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
            <tr class="text-gray-700 dark:text-gray-400">
                <td class="px-4 py-3">
                    <div class="flex items-center text-sm">
                        <div>
                            <p class="font-semibold">@Model.Username</p>
                        </div>
                    </div>
                </td>
                <td class="px-4 py-3 text-sm">
                    @Model.Password
                </td>
                <td class="px-4 py-3 text-sm">
                    @Model.HoTen
                </td>
                <td class="px-4 py-3 text-sm">
                    @Model.Email
                </td>
            </tr>

    </tbody>
</table>

<a class="btn btn-primary col-1" href="/Admin/TaikhoanAdmins/Edit/@Model.Username.Trim()" role="button" style="margin-top:15px;">
    <i class="fas fa-pen-square"></i> Cập nhật</a>