Nhom15/Controllers/DanhMucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom15.Models;

namespace Nhom15.Controllers
{
    public class DanhMucsController : Controller
    {
        private Nhom15DbContext db = new Nhom15DbContext();

        public ActionResult Index()
        {
            return View(db.DanhMucs.ToList());
        }
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<DanhMuc> danhmucs = db.DanhMucs.ToList();
            var danhMuc = danhmucs.Where(d=> d.MaDanhMuc == id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }
    }

}

Nhom15/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom15.Models;

namespace Nhom15.Controllers
{
    public class SanPhamsController : Controller
    {
        private Nhom15DbContext db = new Nhom15DbContext();
        public ActionResult Index(FormCollection form)
        {
            string x = form["searchString"].ToString();
            ViewBag.input = x;
            var ds = db.SanPhams.Where(s => s.TenSP.Contains(x)).ToList();
            return View(ds);
        }
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<SanPham> sanphams = db.SanPhams.ToList();
            var sanPham = sanphams.Where(s => s.MaSP == id).FirstOrDefault();

            if (sanphams == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }
    }
}

Nhom15/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom15.Models;

namespace Nhom15.Controllers
{
    public class TinTucsController : Controller
    {
        private Nhom15DbContext db = new Nhom15DbContext();

        // GET: TinTucs
        public ActionResult Index()
        {
            var tinTucs = db.TinTucs.Include(t => t.TaiKhoanAdmin);
            return View(tinTucs.ToList());
        }

        // GET: TinTucs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.username = new SelectList(db.TaiKhoanAdmins, "username", "password");
            return View();
        }

        // POST: TinTucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTinTuc,Title,NoiDung,username,Anh")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.username = new SelectList(db.TaiKhoanAdmins, "username", "password", tinTuc.Username);
            return View(tinTuc);
        }

        // GET: TinTucs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.username = new SelectList(db.TaiKhoanAdmins, "username", "password", tinTuc.Username);
            return View(tinTuc);
        }

        // POST: TinTucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTinTuc,Title,NoiDung,username,Anh")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tinTuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.username = new SelectList(db.TaiKhoanAdmins, "username", "password", tinTuc.Username);
            return View(tinTuc);
        }

        // GET: TinTucs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Nhom15/Views/Shared/_Layout.cshtml
@using Nhom15.Models
@{
    Nhom15DbContext db = new Nhom15DbContext();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trang web của nhóm 15</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/wwwroot/Client/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/wwwroot/Client/css/animate.css">

    <link rel="stylesheet" href="~/wwwroot/Client/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/wwwroot/Client/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/wwwroot/Client/css/magnific-popup.css">

    <link rel="stylesheet" href="~/wwwroot/Client/css/aos.css">

    <link rel="stylesheet" href="~/wwwroot/Client/css/ionicons.min.css">

    <link rel="stylesheet" href="~/wwwroot/Client/css/bootstrap-datepicker.css" />
    <link rel="stylesheet" href="~/wwwroot/Client/css/jquery.timepicker.css">

    <link rel="stylesheet" href="~/wwwroot/Client/css/flaticon.css">
    <link rel="stylesheet" href="~/wwwroot/Client/css/icomoon.css">
    <link rel="stylesheet" href="~/wwwroot/Client/css/style.css">
    <link rel="stylesheet" href="~/wwwroot/Client/css/search.css"/>

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/wwwroot/Login/css/style.css">

    <script src="~/wwwroot/Client/js/jquery.min.js"></script>
    <script src="~/wwwroot/Client/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/wwwroot/Client/js/popper.min.js"></script>
    <script src="~/wwwroot/Client/js/bootstrap.min.js"></script>
    <script src="~/wwwroot/Client/js/jquery.easing.1.3.js"></script>
    <script src="~/wwwroot/Client/js/jquery.waypoints.min.js"></script>
    <script src="~/wwwroot/Client/js/jquery.stellar.min.js"></script>
    <script src="~/wwwroot/Client/js/owl.carousel.min.js"></script>
    <script src="~/wwwroot/Client/js/jquery.magnific-popup.min.js"></script>
    <script src="~/wwwroot/Client/js/aos.js"></script>
    <script src="~/wwwroot/Client/js/jquery.animateNumber.min.js"></script>
    <script src="~/wwwroot/Client/js/bootstrap-datepicker.js"></script>
    <script src="~/wwwroot/Client/js/scrollax.min.js"></script>
    @*@<script src="~/wwwroot/Client/js/main.js"></script>*@

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/wwwroot/Login/css/style.css">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="goto-here">
    <div style="height:50px;line-height:50px" class="py-1 bg-primary">
        <div class="container">
            <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
                <div class="col-lg-12 d-block">
                    <div class="row d-flex">
                        <div class="col-md pr-3 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                            <span style="font-size: 14px" class="text">+84 989999999</span>
                        </div>
                        <!--<div class="col-md pr-3 d-flex topper align-items-center">-->
                        @*<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
        <span style="color:darkslategrey;font-size:14px" class="text">Liên hệ : Nhom15@Gmail.com</span>*@
                        <!--</div>-->
                        @using (Html.BeginForm("Index", "SanPhams"))
                        {
                            <div class="wrapSearch">
                                <div style="margin-left:-50px" class="search">
                                    <input type="text" name="searchString" class="searchTerm" placeholder="Tìm kiếm">
                                    <button type="submit" class="searchButton">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        }


                        <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                            @if (Session["HoTen"] != null)
                            {
                                <strong>
                                    <span style="font-size:13px" class="text">
                                        <a style="text-decoration:none"
                                           href="@Url.Action("ChiTiet","TaiKhoanKhachHangs")">@Session["HoTen"]</a>
                                        |
                                        <a style="text-decoration:none" href="@Url.Action("ChiTiet","TaiKhoanKhachHangs")">Thông tin tài khoản </a>
                                        |
                                        <a style="text-decoration:none" href="@Url.Action("Logout","Home")">Đăng xuất</a>
                                    </span>
                                </strong>
                            }
                            else
                            {
                                <span class="text">
                                    <a style="text-decoration:none"
                                       href="@Url.Action("DangNhap","TaiKhoanKhachHangs")">Đăng nhập</a>
                                    | <a style="text-decoration:none" href="@Url.Action("Dangky","TaiKhoanKhachHangs")">Đăng ký</a>
                                </span>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index","Home")"><span style="color : forestgreen">FlowerStore</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span>
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="@Url.Action("Index","Home")" class="nav-link">Trang Chủ</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Danh Mục</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            @foreach (var item in db.DanhMucs.ToList())
                            {
                                <a class="dropdown-item" href="@Url.Action("Details", "DanhMucs", new { id = item.MaDanhMuc.Trim() })">@Html.DisplayFor(model => item.TenDanhMuc)</a>
                            }
                        </div>
                    </li>
                    <li class="nav-item"><a href="@Url.Action("Index","ChuongTrinhKhuyenMais")" class="nav-link">Chương trình khuyến mãi</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","TinTucs")" class="nav-link">Blog</a></li>
                    <li class="nav-item"><a href="~/Home/LienHe" class="nav-link">Liên hệ</a></li>
                    @{ 
                        int count = 0;
                        if (Session["User"] != null)
                        {
                            foreach (var item in db.ChiTietGioHangs.ToList())
                            {
                                if (item.Username.ToString() == Session["User"].ToString())
                                {
                                    count++;
                                }
                            }
                        }
                        else
                        {
                            count = 0;
                        }

                    }
                    <li class="nav-item cta cta-colored"><a href="@Url.Action("Index","ChiTietGioHangs")" class="nav-link">Giỏ hàng<span class="icon-shopping_cart"></span>[@count]</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()
    <hr />
    <footer class="ftco-footer ftco-section">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">FlowerStore</h2>
                        <p>Gửi những yêu thương của bạn đến với người thân bằng cách đơn giản nhất</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-5">
                        <h2 class="ftco-heading-2">Liên kết trang web</h2>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">Về chúng tôi</a></li>
                            <li><a href="#" class="py-2 d-block">Blog</a></li>
                            <li><a href="#" class="py-2 d-block">Hướng dẫn chăm sóc hoa</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Chăm sóc khách hàng</h2>
                        <div class="d-flex">
                            <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                                <li><a href="#" class="py-2 d-block">Câu hỏi thường gặp</a></li>
                                <li><a href="#" class="py-2 d-block">Phương thức thanh toán</a></li>
                                <li><a href="#" class="py-2 d-block">Lưu ý chính</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Bạn có câu hỏi ?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">Số 269 Cầu Diễn - Bắc Từ Liêm - Hà Nội</span></li>
                                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+84 989999999</span></a></li>
                                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">Nhom15@Gmail.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> Nhom15
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>

</html>