Nhom15/Models/ChuongTrinhKhuyenMai.cs
namespace Nhom15.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("ChuongTrinhKhuyenMai")]
    public partial class ChuongTrinhKhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuongTrinhKhuyenMai()
        {
            SanPhamKhuyenMais = new HashSet<SanPhamKhuyenMai>();
        }

        [Key]
        [StringLength(10)]
        public string MaChuongTrinh { get; set; }

        [StringLength(500)]
        public string TenChuongTrinh { get; set; }

        public DateTime? NgayBatDau { get; set; }

        public DateTime? NgayKetThuc { get; set; }

        [StringLength(100)]
        public string Anh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamKhuyenMai> SanPhamKhuyenMais { get; set; }
    }
}

Nhom15/Areas/Admin/Controllers/ChuongTrinhKhuyenMaisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom15.Models;
using PagedList;

namespace Nhom15.Areas.Admin.Controllers
{
    public class ChuongTrinhKhuyenMaisController : BaseController
    {
        private Nhom15DbContext db = new Nhom15DbContext();

        // GET: Admin/ChuongTrinhKhuyenMais
        public ActionResult Index(string sortOrder, int? page)
        {
            ViewBag.SaptheoBatdau = String.IsNullOrEmpty(sortOrder) ? "ngaybd_desc" : "";
            ViewBag.SaptheoKetthucs = String.IsNullOrEmpty(sortOrder) ? "ngaykt_desc" : "";

            var CTKM = db.ChuongTrinhKhuyenMais.Select(p => p);

            switch (sortOrder)
            {
                case "ngaybd_desc":
                    CTKM = CTKM.OrderByDescending(s => s.NgayBatDau);
                    break;
                case "ngaykt_desc":
                    CTKM = CTKM.OrderByDescending(s => s.NgayKetThuc);
                    break;
                default:
                    CTKM = CTKM.OrderBy(s => s.MaChuongTrinh);
                    break;
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);

            return View(CTKM.ToPagedList(pageNumber, pageSize));
        }

        //// GET: Admin/ChuongTrinhKhuyenMais/Details/5
        //public ActionResult Details(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ChuongTrinhKhuyenMai chuongTrinhKhuyenMai = db.ChuongTrinhKhuyenMais.Find(id);
        //    if (chuongTrinhKhuyenMai == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(chuongTrinhKhuyenMai);
        //}

        // GET: Admin/ChuongTrinhKhuyenMais/Create
        public ActionResult Create()
        {
            ViewBag.MaChuongTrinh = new SelectList(db.SanPhamKhuyenMais, "MaChuongTrinh", "MaSP");
            return View();
        }

        // POST: Admin/ChuongTrinhKhuyenMais/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ChuongTrinhKhuyenMai chuongTrinhKhuyenMai)
        {
            if (checkKey(chuongTrinhKhuyenMai.MaChuongTrinh) == true)
            {
                ViewBag.Flag = 1;
                return View(chuongTrinhKhuyenMai);
            }
            try
            {
                if (ModelState.IsValid)
                {
                    db.ChuongTrinhKhuyenMais.Add(chuongTrinhKhuyenMai);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(chuongTrinhKhuyenMai);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu " + ex.Message;
                return View(chuongTrinhKhuyenMai);
            }
        }

        // GET: Admin/ChuongTrinhKhuyenMais/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChuongTrinhKhuyenMai chuongTrinhKhuyenMai = db.ChuongTrinhKhuyenMais.Find(id);
            if (chuongTrinhKhuyenMai == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaChuongTrinh = new SelectList(db.SanPhamKhuyenMais, "MaChuongTrinh", "MaSP", chuongTrinhKhuyenMai.MaChuongTrinh);
            return View(chuongTrinhKhuyenMai);
        }

        // POST: Admin/ChuongTrinhKhuyenMais/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaChuongTrinh,TenChuongTrinh,NgayBatDau,NgayKetThuc,Anh")] ChuongTrinhKhuyenMai chuongTrinhKhuyenMai)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chuongTrinhKhuyenMai).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaChuongTrinh = new SelectList(db.SanPhamKhuyenMais, "MaChuongTrinh", "MaSP", chuongTrinhKhuyenMai.MaChuongTrinh);
            return View(chuongTrinhKhuyenMai);
        }

        // GET: Admin/ChuongTrinhKhuyenMais/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChuongTrinhKhuyenMai chuongTrinhKhuyenMai = db.ChuongTrinhKhuyenMais.Find(id);
            if (chuongTrinhKhuyenMai == null)
            {
                return HttpNotFound();
            }
            return View(chuongTrinhKhuyenMai);
        }

        // POST: Admin/ChuongTrinhKhuyenMais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ChuongTrinhKhuyenMai chuongTrinhKhuyenMai = db.ChuongTrinhKhuyenMais.Find(id);
            db.ChuongTrinhKhuyenMais.Remove(chuongTrinhKhuyenMai);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool checkKey(string key)
        {
            return db.DanhMucs.Count(u => u.MaDanhMuc == key) > 0;
        }
    }
}

Nhom15/Controllers/ChuongTrinhKhuyenMaisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom15.Models;

namespace Nhom15.Controllers
{
    public class ChuongTrinhKhuyenMaisController : Controller
    {
        private Nhom15DbContext db = new Nhom15DbContext();

        // GET: ChuongTrinhKhuyenMais
        public ActionResult Index()
        {
            var chuongTrinhKhuyenMais = db.ChuongTrinhKhuyenMais.Include(c => c.SanPhamKhuyenMais);
            return View(chuongTrinhKhuyenMais.ToList());
        }
        public ActionResult ChiTiet(string id)
        {
            List<ChuongTrinhKhuyenMai> CTKM = db.ChuongTrinhKhuyenMais.ToList();
            var ctkm = CTKM.Where(s => s.MaChuongTrinh == id).FirstOrDefault();
            return View(ctkm);
        }
    }
}

Nhom15/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom15.Models;

namespace Nhom15.Controllers
{
    public class SanPhamsController : Controller
    {
        private Nhom15DbContext db = new Nhom15DbContext();
        public ActionResult Index(FormCollection form)
        {
            string x = form["searchString"].ToString();
            ViewBag.input = x;
            var ds = db.SanPhams.Where(s => s.TenSP.Contains(x)).ToList();
            return View(ds);
        }
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<SanPham> sanphams = db.SanPhams.ToList();
            var sanPham = sanphams.Where(s => s.MaSP == id).FirstOrDefault();

            if (sanphams == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }
    }
}

Nhom15/Views/ChuongTrinhKhuyenMais/ChiTiet.cshtml
@model Nhom15.Models.ChuongTrinhKhuyenMai
@using Nhom15.Models
@{
    ViewBag.Title = "ChiTiet";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Nhom15DbContext db = new Nhom15DbContext();
}
<div style="width:57%;height:2000px;margin-left:21%;border:0.5px solid lightgrey">
    <div style="margin:20px auto auto 20px">
        <h2>Chương trình khuyến mãi " <strong> @Html.DisplayFor(model => Model.TenChuongTrinh) </strong> "</h2>
        <hr />
        <p>Đăng bởi : Admin</p>
        <br />
        @{
            string imgPath = "~/wwwroot/Client/images/" + Model.Anh;
        }
        <img src="@Url.Content(imgPath)" style="width:98%;height:100%" class="img-fluid" alt="Colorlib Template">
        <br />
        <h3><strong>1. Thời gian khuyến mãi</strong></h3>
        - Chương trình kéo dài đến ngày @Html.DisplayFor(model => Model.NgayKetThuc)
        - Chương trình có thể kết thúc sớm nếu hết quà tặng
        <h3><strong>Danh sách sản phẩm khuyến mãi</strong></h3>
        @foreach (var item in db.SanPhamKhuyenMais)
        {
            if (Model.MaChuongTrinh == item.MaChuongTrinh)
            {
    <div class="col-md-6 col-lg-3 ftco-animate">
        <div class="product">
            <div class="img-prod">
                @{
                    string imgP = "~/wwwroot/Client/images/" + item.SanPham.Anh;
                }
                <a href="@Url.Action("Details","SanPhams", new { id = item.SanPham.MaSP })"><img class="img-fluid" src="@Url.Content(imgP)" style="width:235px;height:255px" alt="Colorlib Template"></a>
            </div>
            <div class="text py-3 pb-4 px-3 text-center">
                <h3><a href="@Url.Action("Details","SanPhams", new { id = item.SanPham.MaSP })">@Html.DisplayFor(model => item.SanPham.TenSP)</a></h3>
                <div class="d-flex">
                    <div class="pricing">
                        <p class="price"><span class="price-sale">@Html.DisplayFor(model => item.SanPham.DonGia)</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
            }

        }

    </div>
</div>

Nhom15/Views/ChuongTrinhKhuyenMais/Index.cshtml
@model IEnumerable<Nhom15.Models.ChuongTrinhKhuyenMai>

@section Scripts{
    <script src="~/wwwroot/Client/js/jquery.min.js"></script>
    <script src="~/wwwroot/Client/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/wwwroot/Client/js/popper.min.js"></script>
    <script src="~/wwwroot/Client/js/bootstrap.min.js"></script>
    <script src="~/wwwroot/Client/js/jquery.easing.1.3.js"></script>
    <script src="~/wwwroot/Client/js/jquery.waypoints.min.js"></script>
    <script src="~/wwwroot/Client/js/jquery.stellar.min.js"></script>
    <script src="~/wwwroot/Client/js/owl.carousel.min.js"></script>
    <script src="~/wwwroot/Client/js/jquery.magnific-popup.min.js"></script>
    <script src="~/wwwroot/Client/js/aos.js"></script>
    <script src="~/wwwroot/Client/js/jquery.animateNumber.min.js"></script>
    <script src="~/wwwroot/Client/js/bootstrap-datepicker.js"></script>
    <script src="~/wwwroot/Client/js/scrollax.min.js"></script>
    @*<script src="~/wwwroot/Client/js/google-map.js"></script>*@
    <script src="~/wwwroot/Client/js/main.js"></script>
}
<body class="goto-here">
    <section class="ftco-section ftco-degree-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 ftco-animate">
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            <div class="col-md-12 d-flex ftco-animate">
                                <div class="blog-entry align-self-stretch d-md-flex">
                                    @{
                                        string imgPath = "~/wwwroot/Client/images/" + item.Anh;
                                    }
                                    <div class="block-20" style="background-image: url(@Url.Content(imgPath));width:500px;height:150px"></div>
                                    <div class="text d-block pl-md-4">
                                        <div class="meta mb-3">
                                            <div><a href="@Url.Action("ChiTiet","ChuongTrinhKhuyenMais", new { id = item.MaChuongTrinh })"><h3>@Html.DisplayFor(model => item.TenChuongTrinh)</h3></a></div>
                                        </div>
                                        <p>@Html.DisplayFor(model => item.NgayBatDau)</p>
                                        <p>@Html.DisplayFor(model => item.NgayKetThuc)</p>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div> <!-- .col-md-8 -->
                <div class="col-lg-4 sidebar ftco-animate">
                    <div class="sidebar-box">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <button style="height:100%; width:50px;border:0.5px solid lightgrey" class="icon ion-ios-search"></button>
                                <input type="text" class="form-control" placeholder="Search...">
                            </div>
                        </form>
                    </div>

                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading">Tin tức mới</h3>
                        @foreach (var item in Model)
                        {
                            DateTime s = (DateTime)item.NgayKetThuc;
                            if (DateTime.Now.DayOfYear - s.DayOfYear < 7)
                            {
                                <div class="col-md-12 d-flex ftco-animate">
                                    <div class="blog-entry align-self-stretch d-md-flex">
                                        @{
                                            string imgPath = "~/wwwroot/Client/images/" + item.Anh;
                                        }
                                        <div class="block-20" style="background-image: url(@Url.Content(imgPath));"></div>
                                        <div class="text d-block pl-md-4">
                                            <div class="meta mb-3">
                                                <div><a href="#">@Html.DisplayFor(model => item.MaChuongTrinh)</a></div>
                                                <div><a href="#">@Html.DisplayFor(model => item.TenChuongTrinh)</a></div>
                                            </div>
                                            <p>@Html.DisplayFor(model => item.NgayBatDau)</p>
                                            <p>@Html.DisplayFor(model => item.NgayKetThuc)</p>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>

            </div>
        </div>
    </section>
</body>